Repository 202212-GIZ-YE-FEW/Web_Wizards_Pebble, pull requests merged in 2023-05, with the labels that each got.

#127 91 develop event creation page event type buttons
  src/components/LocationSelector/EventCreation.jsx
  src/components/LocationSelector/__test__/__snapshots__/EventCreation.test.js.snap
  src/components/Navbar.jsx
  src/components/__tests__/__snapshots__/Attendees.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDescription.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDetails.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleDetail.test.jsx.snap
  src/components/__tests__/__snapshots__/Title.test.jsx.snap
  src/components/event/Attendees.jsx
  src/components/event/EventDescription.jsx
  src/components/event/EventDetails.jsx
  src/components/event/EventImage.jsx
  src/components/event/SingleDetail.jsx
  src/components/event/Title.jsx
  src/pages/events/[id]/index.js
Labels: enhancement, API

#128 77 devolop events view page add sorting functionalitys
  src/components/LocationSelector/__test__/EventCreation.test.js
  src/firebase/firestorage.js
  src/pages/events/index.js
Labels: API, authentication

#134 fix(about page): fixes some bugs
  public/Images/team/abdullah.png
  public/Images/team/adeeb.png
  public/Images/team/azzam.png
  public/Images/team/bakeel.png
  public/Images/team/sufyan.png
  public/images/about.png
  public/images/adeeb.png
  public/locales/ar/about.json
  public/locales/en/about.json
  public/teamInfo.json
  src/components/Tech.jsx
  src/components/__tests__/About.test.jsx
  src/components/__tests__/Team.test.jsx
  src/components/__tests__/Tech.test.jsx
  src/components/__tests__/__snapshots__/Team.test.jsx.snap
  src/components/__tests__/__snapshots__/Tech.test.jsx.snap
  src/components/about/About.jsx
  src/components/about/Team.jsx
  src/components/about/Tech.jsx
  src/pages/about/index.js
Labels: bug

#135 Events page
  src/components/__tests__/__snapshots__/EventDate.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDetails.test.jsx.snap
  src/components/__tests__/__snapshots__/JoinButton.test.jsx.snap
  src/components/__tests__/__snapshots__/SignUpForm.test.jsx.snap
  src/components/event/EventDetails.jsx
  src/components/event/JoinButton.jsx
  src/components/events/EventCard/EventCard.jsx
  src/components/events/EventCard/EventDate.jsx
  src/pages/events/[id]/index.js
  src/pages/events/create.jsx
Labels: enhancement, API, authentication

#136 feat(404 page): add 404 page
  public/images/404.png
  public/images/404.png:Zone.Identifier
  src/components/LocationSelector/EventCreation.jsx
  src/pages/404.jsx
Labels: enhancement

#137 fix(eventdate): updated EventDate component to handle Unix timestamps
  src/components/LocationSelector/EventCreation.jsx
  src/components/events/EventCard/EventDate.jsx
Labels: bug, enhancement, API

#138 77 devolop events view page add sorting functionalitys
  src/components/events/DatePicker/DateRangePicker.jsx
  src/components/events/DatePicker/DateRangePicker.module.scss
  src/pages/events/index.js
Labels: bug

#140 72 develop event creation page
  src/components/LocationSelector/EventCreation.jsx
  src/components/LocationSelector/__test__/__snapshots__/EventCreation.test.js.snap
  src/components/__tests__/__snapshots__/Interests.test.jsx.snap
  src/components/editProfile/Interests.jsx
  src/pages/events/create.jsx
Labels: bug

#143 Events page
  src/components/LocationSelector/YemenCities.js
  src/components/__tests__/__snapshots__/EventAttendees.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDetails.test.jsx.snap
  src/components/events/DatePicker/DateRangePicker.jsx
  src/components/events/EventCard/EventAttendees.jsx
  src/components/events/EventCard/EventCard.jsx
  src/components/events/EventCard/EventsImage.jsx
  src/pages/events/index.js
Labels: bug

#148 fix(homepage): bugs fixes
  src/components/How.jsx
  src/components/__tests__/__snapshots__/How.test.jsx.snap
Labels: bug
