Repository 202212-GIZ-YE-FEW/Web_Wizards_Pebble, pull requests merged in 2023-04, with the labels that each got.

#35 feat(layout): setup of navbar and footer
  public/locales/ar/common.json
  public/locales/en/common.json
  public/logo.svg
  src/components/Footer.jsx
  src/components/Logo.jsx
  src/components/Navbar.jsx
  src/components/__tests__/Footer.test.jsx
  src/components/__tests__/Logo.test.jsx
  src/components/__tests__/__snapshots__/Footer.test.jsx.snap
  src/components/__tests__/__snapshots__/Logo.test.jsx.snap
  src/layout/Layout.jsx
  src/pages/404.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
  src/styles/globals.css
Labels: enhancement

#40 Future created Sign up-in title component with it's …
  src/components/SignTitle.jsx
  src/components/__tests__/SignTitle.test.jsx
  src/components/__tests__/__snapshots__/SignTitle.test.jsx.snap
Labels: enhancement

#44 Feature: created buttons component create buttons and OR divider
  src/components/ButtonAuth.jsx
  src/components/ButtonAuth.module.css
  src/components/OrDivider.jsx
  src/components/SignOptions.jsx
  src/components/__tests__/ButtonAuth.test.jsx
  src/components/__tests__/OrDivider.test.jsx
  src/components/__tests__/SignOptions.test.jsx
  src/components/__tests__/__snapshots__/ButtonAuth.test.jsx.snap
  src/components/__tests__/__snapshots__/OrDivider.test.jsx.snap
  src/components/__tests__/__snapshots__/SignOptions.test.jsx.snap
Labels: enhancement

#47 chore: better setup
  .github/auto_assign.yml
  .github/pull_request_template.md
  next-sitemap.config.js
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
Labels: enhancement

#50 feat(created edit profile page components): designed profile image with buttons
  public/locales/ar/editprofile.json
  public/locales/en/editprofile.json
  src/components/CircleImg.jsx
  src/components/EditProfileButton.jsx
  src/components/SaveButton.jsx
  src/components/__tests__/CircleImg.test.jsx
  src/components/__tests__/EditProfileButton.test.jsx
  src/components/__tests__/SaveButton.test.jsx
  src/components/__tests__/__snapshots__/CircleImg.test.jsx.snap
  src/components/__tests__/__snapshots__/EditProfileButton.test.jsx.snap
  src/components/__tests__/__snapshots__/SaveButton.test.jsx.snap
  src/pages/editprofile/index.jsx
Labels: enhancement

#51 feat(landing): add `sustainable development goals` section
  public/landing/goal1.svg
  public/landing/goal10.svg
  public/landing/goal11.svg
  public/landing/goal12.svg
  public/landing/goal13.svg
  public/landing/goal14.svg
  public/landing/goal15.svg
  public/landing/goal16.svg
  public/landing/goal17.svg
  public/landing/goal2.svg
  public/landing/goal3.svg
  public/landing/goal4.svg
  public/landing/goal5.svg
  public/landing/goal6.svg
  public/landing/goal7.svg
  public/landing/goal8.svg
  public/landing/goal9.svg
  public/landing/wheel.svg
  public/locales/ar/landing.json
  public/locales/en/landing.json
  src/components/Footer.jsx
  src/components/Goals.jsx
  src/components/How.jsx
  src/components/__tests__/Goals.test.jsx
  src/components/__tests__/__snapshots__/Footer.test.jsx.snap
  src/components/__tests__/__snapshots__/Goals.test.jsx.snap
  src/components/__tests__/mini/__snapshots__/Title.test.jsx.snap
  src/components/mini/index.jsx
  src/pages/index.jsx
  tailwind.config.js
Labels: enhancement

#52 feat(edit profile page): created Edit profile user fileds (Name, Location)
  public/locales/ar/editprofile.json
  public/locales/en/editprofile.json
  src/components/EditProfileForm.jsx
  src/components/SecondaryTitle.jsx
  src/components/__tests__/EditProfileForm.test.jsx
  src/components/__tests__/SecondaryTitle.test.jsx
  src/components/__tests__/__snapshots__/EditProfileForm.test.jsx.snap
  src/components/__tests__/__snapshots__/SecondaryTitle.test.jsx.snap
  src/pages/editprofile/index.jsx
Labels: enhancement

#53 feat(edit profile page): created Interests components
  public/locales/ar/editprofile.json
  public/locales/en/editprofile.json
  src/components/Interests.jsx
  src/components/SingleInterest.jsx
  src/components/SingleInterest.test.jsx
  src/components/__snapshots__/SingleInterest.test.jsx.snap
  src/components/__tests__/Interests.test.jsx
  src/components/__tests__/__snapshots__/Interests.test.jsx.snap
  src/pages/editprofile/index.jsx
Labels: enhancement

#54 feat(edit profile page): added Save button component
  src/pages/editprofile/index.jsx
Labels: enhancement

#55 feat(landing): add `volunteers` section
  public/landing/volunteer.svg
  public/locales/ar/landing.json
  public/locales/en/landing.json
  src/components/Volunteers.jsx
  src/components/__tests__/Volunteers.test.jsx
  src/components/__tests__/__snapshots__/Volunteers.test.jsx.snap
  src/components/__tests__/mini/Description.test.jsx
  src/components/__tests__/mini/RoundedImage.test.jsx
  src/components/__tests__/mini/__snapshots__/Description.test.jsx.snap
  src/components/__tests__/mini/__snapshots__/RoundedImage.test.jsx.snap
  src/components/mini/index.jsx
  src/pages/index.jsx
Labels: enhancement

#57 feat(edit profile page): created component for designing the change password
  public/locales/ar/editprofile.json
  public/locales/en/editprofile.json
  src/components/ChangePasswordForm.jsx
  src/components/__tests__/ChangePasswordForm.test.jsx
  src/components/__tests__/__snapshots__/ChangePasswordForm.test.jsx.snap
  src/pages/editprofile/index.jsx
Labels: enhancement

#64 33 event creation add header component
  public/locales/ar/locationSelector.json
  public/locales/en/locationSelector.json
  src/components/LocationSelector/LocationInput.jsx
  src/components/LocationSelector/LocationSelector.jsx
  src/components/LocationSelector/__test__/LocationInput.test.js
  src/components/LocationSelector/__test__/LocationSelector.test.js
  src/components/LocationSelector/__test__/__snapshots__/LocationInput.test.js.snap
  src/components/LocationSelector/__test__/__snapshots__/LocationSelector.test.js.snap
  src/pages/events/create.jsx
Labels: enhancement

#66 Feature/firebase configuration
  firebase.config.js
  firebase.json
  jsconfig.json
  lib/useFirestore.js
  package-lock.json
  package.json
Labels: enhancement

#62 feat(about-page): add header image
  public/images/about.png
  src/components/About.jsx
  src/components/__tests__/About.test.jsx
  src/components/__tests__/__snapshots__/About.test.jsx.snap
  src/pages/about.jsx
Labels: enhancement

#90 feat(event view page): created the components needed to view details of event
  public/event/Wave.png
  src/components/__tests__/EventDetails.test.jsx
  src/components/__tests__/EventImage.test.jsx
  src/components/__tests__/JoinButton.test.jsx
  src/components/__tests__/SingleDetail.test.jsx
  src/components/__tests__/__snapshots__/EventDetails.test.jsx.snap
  src/components/__tests__/__snapshots__/EventImage.test.jsx.snap
  src/components/__tests__/__snapshots__/JoinButton.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleDetail.test.jsx.snap
  src/components/event/EventDetails.jsx
  src/components/event/EventImage.jsx
  src/components/event/JoinButton.jsx
  src/components/event/SingleDetail.jsx
  src/pages/event/index.js
Labels: enhancement

#97 feat(event view page): created component for event description
  src/components/LocationSelector/LocationSelector.jsx
  src/components/__tests__/EventDescription.test.jsx
  src/components/__tests__/Title.test.jsx
  src/components/__tests__/__snapshots__/EventDescription.test.jsx.snap
  src/components/__tests__/__snapshots__/Title.test.jsx.snap
  src/components/event/EventDescription.jsx
  src/components/event/Title.jsx
  src/pages/event/index.js
Labels: enhancement

#98 30 edit profile page add interests component
  public/locales/ar/editprofile.json
  public/locales/en/editprofile.json
  src/components/ButtonAuth.jsx
  src/components/__tests__/ChangePasswordForm.test.jsx
  src/components/__tests__/CircleImg.test.jsx
  src/components/__tests__/EditProfileButton.test.jsx
  src/components/__tests__/EditProfileForm.test.jsx
  src/components/__tests__/Interests.test.jsx
  src/components/__tests__/SaveButton.test.jsx
  src/components/__tests__/SecondaryTitle.test.jsx
  src/components/__tests__/SingleInterest.test.jsx
  src/components/__tests__/__snapshots__/Interests.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleInterest.test.jsx.snap
  src/components/editProfile/ChangePasswordForm.jsx
  src/components/editProfile/CircleImg.jsx
  src/components/editProfile/EditProfileButton.jsx
  src/components/editProfile/EditProfileForm.jsx
  src/components/editProfile/Interests.jsx
  src/components/editProfile/SaveButton.jsx
  src/components/editProfile/SecondaryTitle.jsx
  src/components/editProfile/SingleInterest.jsx
  src/pages/editprofile/index.jsx
  wget-log
Labels: documentation, enhancement

#101 docs(delete unnecessary file): delete wget-log file
  wget-log
Labels: documentation

#102 22 event page add attendees component
  et --hard f3d9aab9567dca6fdf0c40d4d94ed82f8519009e
  src/components/__tests__/Attendees.test.jsx
  src/components/__tests__/SingleAttendees.test.jsx
  src/components/__tests__/__snapshots__/Attendees.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDescription.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleAttendees.test.jsx.snap
  src/components/event/Attendees.jsx
  src/components/event/EventDescription.jsx
  src/components/event/SingleAttendees.jsx
  src/pages/event/index.js
Labels: enhancement

#103 100 event title component
  src/components/LocationSelector/EventCreation.jsx
  src/components/LocationSelector/LocationInput.jsx
  src/components/LocationSelector/__test__/__snapshots__/EventCreation.test.js.snap
  src/components/LocationSelector/__test__/__snapshots__/LocationInput.test.js.snap
  src/components/LocationSelector/__test__/__snapshots__/LocationSelector.test.js.snap
Labels: enhancement

#112 83 develop sign up page sign up with google
  lib/useAuth.js
  next.config.js
  src/components/__tests__/__snapshots__/SignInForm.test.jsx.snap
  src/components/__tests__/__snapshots__/SignOptions.test.jsx.snap
  src/components/__tests__/__snapshots__/SignUpForm.test.jsx.snap
  src/components/shared/SignOptions.jsx
Labels: enhancement, API, authentication

#113 84 develop sign up page sign up with twitter
  lib/useAuth.js
  src/components/__tests__/__snapshots__/SignInForm.test.jsx.snap
  src/components/__tests__/__snapshots__/SignOptions.test.jsx.snap
  src/components/__tests__/__snapshots__/SignUpForm.test.jsx.snap
  src/components/shared/SignOptions.jsx
Labels: enhancement, API, authentication

#116 75 devolop events view page display personalized greeting using firebase name
  src/pages/events/index.js
Labels: enhancement, authentication

#118 refactor(editprofile): responsive deisgn
  public/locales/en/editprofile.json
  src/components/__tests__/__snapshots__/ChangePasswordForm.test.jsx.snap
  src/components/__tests__/__snapshots__/CircleImg.test.jsx.snap
  src/components/__tests__/__snapshots__/EditProfileButton.test.jsx.snap
  src/components/__tests__/__snapshots__/Interests.test.jsx.snap
  src/components/__tests__/__snapshots__/SaveButton.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleInterest.test.jsx.snap
  src/components/editProfile/ChangePasswordForm.jsx
  src/components/editProfile/CircleImg.jsx
  src/components/editProfile/EditProfileButton.jsx
  src/components/editProfile/EditProfileForm.jsx
  src/components/editProfile/Interests.jsx
  src/components/editProfile/SaveButton.jsx
  src/components/editProfile/SingleInterest.jsx
  src/pages/editprofile/index.jsx
Labels: enhancement

#121 76 devolop events view page get event details from firebase and show on card
  src/components/__tests__/EventAttendees.test.jsx
  src/components/__tests__/EventDate.test.jsx
  src/components/__tests__/EventsDescription.test.jsx
  src/components/__tests__/EventsImage.test.jsx
  src/components/__tests__/EventsTitle.test.jsx
  src/components/__tests__/__snapshots__/About.test.jsx.snap
  src/components/__tests__/__snapshots__/Attendees.test.jsx.snap
  src/components/__tests__/__snapshots__/AuthErrorBox.test.jsx.snap
  src/components/__tests__/__snapshots__/ButtonAuth.test.jsx.snap
  src/components/__tests__/__snapshots__/ChangePasswordForm.test.jsx.snap
  src/components/__tests__/__snapshots__/CircleImg.test.jsx.snap
  src/components/__tests__/__snapshots__/EditProfileButton.test.jsx.snap
  src/components/__tests__/__snapshots__/EditProfileForm.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDescription.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDetails.test.jsx.snap
  src/components/__tests__/__snapshots__/EventImage.test.jsx.snap
  src/components/__tests__/__snapshots__/Footer.test.jsx.snap
  src/components/__tests__/__snapshots__/FormFooter.test.jsx.snap
  src/components/__tests__/__snapshots__/Gallery.test.jsx.snap
  src/components/__tests__/__snapshots__/Goals.test.jsx.snap
  src/components/__tests__/__snapshots__/Hero.test.jsx.snap
  src/components/__tests__/__snapshots__/How.test.jsx.snap
  src/components/__tests__/__snapshots__/InputForm.test.jsx.snap
  src/components/__tests__/__snapshots__/Interests.test.jsx.snap
  src/components/__tests__/__snapshots__/JoinButton.test.jsx.snap
  src/components/__tests__/__snapshots__/Logo.test.jsx.snap
  src/components/__tests__/__snapshots__/Navbar.test.jsx.snap
  src/components/__tests__/__snapshots__/NotVerified.test.jsx.snap
  src/components/__tests__/__snapshots__/OrDivider.test.jsx.snap
  src/components/__tests__/__snapshots__/SaveButton.test.jsx.snap
  src/components/__tests__/__snapshots__/SecondaryTitle.test.jsx.snap
  src/components/__tests__/__snapshots__/SignButton.test.jsx.snap
  src/components/__tests__/__snapshots__/SignInForm.test.jsx.snap
  src/components/__tests__/__snapshots__/SignOptions.test.jsx.snap
  src/components/__tests__/__snapshots__/SignTitle.test.jsx.snap
  src/components/__tests__/__snapshots__/SignUpForm.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleAttendees.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleDetail.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleInterest.test.jsx.snap
  src/components/__tests__/__snapshots__/Sittingimg.test.jsx.snap
  src/components/__tests__/__snapshots__/Team.test.jsx.snap
  src/components/__tests__/__snapshots__/Tech.test.jsx.snap
  src/components/__tests__/__snapshots__/Title.test.jsx.snap
  src/components/__tests__/__snapshots__/Volunteers.test.jsx.snap
  src/components/events/EventCard/EventAttendees.jsx
  src/components/events/EventCard/EventCard.jsx
  src/components/events/EventCard/EventDate.jsx
  src/components/events/EventCard/EventsDescription.jsx
  src/components/events/EventCard/EventsImage.jsx
  src/components/events/EventCard/EventsTitle.jsx
  src/pages/events/index.js
Labels: API, authentication

#123 92 develop event creation page select event location
  src/components/LocationSelector/EventCreation.jsx
  src/components/LocationSelector/__test__/__snapshots__/EventCreation.test.js.snap
  src/components/__tests__/__snapshots__/About.test.jsx.snap
  src/components/__tests__/__snapshots__/Attendees.test.jsx.snap
  src/components/__tests__/__snapshots__/AuthErrorBox.test.jsx.snap
  src/components/__tests__/__snapshots__/ButtonAuth.test.jsx.snap
  src/components/__tests__/__snapshots__/ChangePasswordForm.test.jsx.snap
  src/components/__tests__/__snapshots__/CircleImg.test.jsx.snap
  src/components/__tests__/__snapshots__/EditProfileButton.test.jsx.snap
  src/components/__tests__/__snapshots__/EditProfileForm.test.jsx.snap
  src/components/__tests__/__snapshots__/EventAttendees.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDate.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDescription.test.jsx.snap
  src/components/__tests__/__snapshots__/EventDetails.test.jsx.snap
  src/components/__tests__/__snapshots__/EventImage.test.jsx.snap
  src/components/__tests__/__snapshots__/EventsDescription.test.jsx.snap
  src/components/__tests__/__snapshots__/EventsImage.test.jsx.snap
  src/components/__tests__/__snapshots__/EventsTitle.test.jsx.snap
  src/components/__tests__/__snapshots__/Footer.test.jsx.snap
  src/components/__tests__/__snapshots__/FormFooter.test.jsx.snap
  src/components/__tests__/__snapshots__/Gallery.test.jsx.snap
  src/components/__tests__/__snapshots__/Goals.test.jsx.snap
  src/components/__tests__/__snapshots__/Hero.test.jsx.snap
  src/components/__tests__/__snapshots__/How.test.jsx.snap
  src/components/__tests__/__snapshots__/InputForm.test.jsx.snap
  src/components/__tests__/__snapshots__/Interests.test.jsx.snap
  src/components/__tests__/__snapshots__/JoinButton.test.jsx.snap
  src/components/__tests__/__snapshots__/Logo.test.jsx.snap
  src/components/__tests__/__snapshots__/Navbar.test.jsx.snap
  src/components/__tests__/__snapshots__/NotVerified.test.jsx.snap
  src/components/__tests__/__snapshots__/OrDivider.test.jsx.snap
  src/components/__tests__/__snapshots__/SaveButton.test.jsx.snap
  src/components/__tests__/__snapshots__/SecondaryTitle.test.jsx.snap
  src/components/__tests__/__snapshots__/SignButton.test.jsx.snap
  src/components/__tests__/__snapshots__/SignInForm.test.jsx.snap
  src/components/__tests__/__snapshots__/SignOptions.test.jsx.snap
  src/components/__tests__/__snapshots__/SignTitle.test.jsx.snap
  src/components/__tests__/__snapshots__/SignUpForm.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleAttendees.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleDetail.test.jsx.snap
  src/components/__tests__/__snapshots__/SingleInterest.test.jsx.snap
  src/components/__tests__/__snapshots__/Sittingimg.test.jsx.snap
  src/components/__tests__/__snapshots__/Team.test.jsx.snap
  src/components/__tests__/__snapshots__/Tech.test.jsx.snap
  src/components/__tests__/__snapshots__/Title.test.jsx.snap
  src/components/__tests__/__snapshots__/Volunteers.test.jsx.snap
Labels: API

#124 72 develop event creation page
  lib/useFirebaseStorage.js
  public/locales/ar/eventCreation.json
  public/locales/en/eventCreation.json
  src/components/LocationSelector/EventCreation.jsx
  src/components/LocationSelector/__test__/EventCreation.test.js
  src/components/LocationSelector/__test__/__snapshots__/EventCreation.test.js.snap
Labels: enhancement, ui, firebase
